version: '3'

services:
  calendara-dev:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: npm run dev