apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-auth
stringData:
  clientId: {{ .Values.clientId }}
  clientSecret: {{ .Values.clientSecret }}
  redirectUrl: {{ .Values.redirectUrl }}
  profileUrl: {{ .Values.profileUrl }}
  mongoUri: {{ .Values.mongoUri }}
  apiUrl: {{ .Values.apiUrl }}
  jwtSecret: {{ .Values.jwtSecret }}
  apiVersion: {{ .Values.apiVersion }}
  port: "{{ .Values.port }}"